import Link from "next/link";
import type { Dictionary, Locale } from "@/data/dictionaries";
import { SiteHeader, SiteFooter } from "@/components/layout/SiteChrome";
import { SceneSection, TickList } from "@/components/layout/SceneSection";
import { Reveal, CtaLink } from "@/components/ui/Reveal";
import { IconSprout, IconHarvest, IconFactory, IconEarth, IconSoil, IconWater, IconGrass, IconSheaf, IconGear, IconCarbonLeaf, IconCoins, IconPlanet, IconCommunity, IconCycle, IconFuture } from "@/components/ui/icons";

function PathIcon({ index, className = "h-8 w-8" }: { index: number; className?: string }) {
  const paths = [
    <><path d="M4 18h16M6 15c3-1 3-5 6-9 3 4 3 8 6 9" /><path d="M12 6v12" /></>,
    <><path d="M4 17h16M6 13l4-4 3 2 5-6" /><path d="M15 5h3v3" /></>,
    <><circle cx="12" cy="12" r="7" /><path d="M12 8v4l3 2M12 2v3" /></>,
    <><path d="M5 18V9l7-4 7 4v9M3 18h18" /><path d="M9 18v-5h6v5" /></>,
    <><path d="M12 3v18M5 8h14M7 8c0 3-2 5-4 5M17 8c0 3 2 5 4 5" /><circle cx="12" cy="5" r="2" /></>,
    <><path d="M6 19V9M12 19V5M18 19v-7" /><path d="M4 19h16" /></>,
    <><path d="M4 14c4-5 7-5 11-1l5-6" /><path d="M16 7h4v4" /><circle cx="7" cy="17" r="2" /></>,
    <><path d="M12 20V10" /><path d="M12 12c-4 0-6-2-6-6 4 0 6 2 6 6ZM12 15c4 0 6-2 6-6-4 0-6 2-6 6Z" /></>,
    <><circle cx="8" cy="8" r="3" /><circle cx="16" cy="16" r="3" /><path d="M10 10l4 4M14 6h5v5" /></>,
    <><path d="M12 3l7 4v5c0 4-3 7-7 9-4-2-7-5-7-9V7l7-4Z" /><path d="m9 12 2 2 4-5" /></>,
  ];
  return <svg viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[index % paths.length]}</svg>;
}

export function HomeLanding({ dict, locale }: { dict: Dictionary; locale: Locale }) {
  const p = (path: string) => `/${locale}${path}`;
  const h = dict.home;
  const pages = dict.pages;
  const siteLabelUnused = (_href: string) => "";
  const ep = dict.nav.entryPoints;
  const routes = [
    ["01", ep[0]?.label ?? "Ризоми", "/buy-rhizomes"],
    ["02", ep[1]?.label ?? "Відновити землю", "/regional-pilots"],
    ["03", ep[2]?.label ?? "Net Zero", "/net-zero"],
    ["04", ep[3]?.label ?? "Промисловість та збут", "/industry-offtake"],
    ["05", ep[4]?.label ?? "Horizon та гранти", "/horizon-grants"],
    ["06", ep[5]?.label ?? "Інвестувати", "/investors"],
    ["07", ep[6]?.label ?? "Регіональний партнер", "/franchise"],
    ["08", ep[7]?.label ?? "Міжнародний партнер", "/consortium"],
  ] as const;

  return <main className="min-h-svh bg-carbon">
    <SiteHeader dict={dict} locale={locale} />
    <div className="continuous-opening">
    <section className="hero-scene relative flex min-h-svh items-end overflow-hidden pt-24">
      <div aria-hidden className="absolute inset-0 bg-cover brightness-[.98] saturate-[1.1]" style={{ backgroundImage: "url(/images/hero-roots-continuous-v2.png)", backgroundPosition: "center top" }} />
      <div aria-hidden className="absolute inset-0 bg-[linear-gradient(90deg,rgba(245,242,234,.92)_0%,rgba(245,242,234,.5)_38%,rgba(245,242,234,0)_64%),linear-gradient(0deg,rgba(245,242,234,.85)_0%,transparent_40%,rgba(245,242,234,.15)_100%)]" />
      <div aria-hidden className="scene-grain absolute inset-0 opacity-30" />
      <div className="relative mx-auto flex w-full max-w-[1440px] flex-col justify-end px-6 pb-8 sm:px-10 lg:px-14 lg:pb-10">
        <div className="grid items-end gap-12 lg:grid-cols-[1fr_380px]">
          <Reveal><div className="flex items-center gap-4 text-biomass"><span className="font-sans text-xl font-light">01</span><span className="h-px w-9 bg-biomass" /></div><h1 className="mt-6 max-w-5xl font-sans text-[clamp(3.2rem,7.3vw,7.7rem)] font-extralight uppercase leading-[0.95] tracking-[-0.02em] text-stone-50">{h.hero.titleLines[0]}<br /><span className="text-stone-100">{h.hero.titleLines[1]}</span></h1><p className="mt-7 whitespace-nowrap text-[10px] font-semibold tracking-[0.22em] text-biomass uppercase sm:text-[11px] sm:tracking-[0.26em]">Regenerative bioeconomy · Circular economy · Low-carbon industry</p><p className="mt-5 max-w-lg text-[15px] leading-7 text-stone-300">{h.hero.lead}</p><div className="mt-8 flex flex-wrap gap-3"><CtaLink href={p("/buy-rhizomes")}>{h.rhizomes.ctaPrimary}<span aria-hidden>→</span></CtaLink><CtaLink href={p("/about")} variant="outline">{locale === "uk" ? "Про нас" : "About us"}</CtaLink></div></Reveal>
          <Reveal delay={0.18} className="hero-availability hidden border-l border-[#d5b36d] bg-[linear-gradient(90deg,rgba(5,17,12,.58),rgba(5,17,12,.08))] px-8 py-7 backdrop-blur-[2px] lg:block"><p className="font-serif text-5xl font-normal leading-none text-[#f0d394] drop-shadow-[0_2px_16px_rgba(0,0,0,.8)]">30 MILLION</p><p className="mt-3 font-serif text-3xl font-normal uppercase leading-[1.05] text-white drop-shadow-[0_2px_16px_rgba(0,0,0,.9)]">Rhizomes<br />available now</p></Reveal>
        </div>
        <Reveal delay={0.3} className="mt-10"><nav aria-label="Primary paths" className="grid border border-white/10 bg-black/20 backdrop-blur-sm sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{routes.map(([num, label, href], i) => <Link key={href} href={p(href)} className="group flex min-h-24 flex-col justify-center gap-3 border-b border-r border-white/10 px-4 py-3 transition-colors hover:bg-biomass hover:text-[#1c1408]"><span className="text-biomass group-hover:text-[#1c1408]/70"><PathIcon index={i} className="h-6 w-6" /></span><span className="text-[10px] text-biomass/80 group-hover:text-[#1c1408]/60">{num}</span><span className="text-[11px] font-semibold leading-4">{label}</span></Link>)}</nav></Reveal>
      </div>
    </section>

    <SceneSection num="02" eyebrow="Міскантус: від землі до системи" title={locale === "uk" ? "Від землі до системи" : "From soil to system"} lead={pages.about.lead} image="/images/hero-roots-continuous-v2.png" imagePosition="center bottom"><p className="max-w-lg border-l border-biomass/60 pl-5 text-sm leading-6 text-stone-300">{dict.brand.promise}. {pages.technologies.lead}</p></SceneSection>
    </div>
    <SceneSection num="03" eyebrow={pages.agronomicSupport.title} title={pages.agronomicSupport.subtitle} lead={pages.agronomicSupport.lead} image="/images/agronomists-v2.png" imagePosition="66% center" cta={dict.forms.configs.agronomic.submit} href={p("/agronomic-support")}><TickList items={pages.agronomicSupport.tools} /></SceneSection>
    <SceneSection num="04" eyebrow={locale === "uk" ? "Механізація повного циклу" : "Full-cycle mechanisation"} title={locale === "uk" ? "Підбір обладнання" : "Equipment selection"} lead={pages.equipment.lead} image="/images/equipment-harvester-v2.png" imagePosition="75% center" cta={dict.forms.configs.equipment.submit} href={p("/equipment")} wide cornerLeft={h.hero.cornerTagline} cornerRight={`${h.final.big[0]}. ${h.final.big[1]}.`}><p className="text-[15px] font-medium text-stone-100">{pages.equipment.subtitle}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[{t: pages.equipment.plantingTitle, x: pages.equipment.planting, I: IconSprout}, {t: pages.equipment.harvestTitle, x: pages.equipment.harvest, I: IconHarvest}, {t: pages.equipment.processingTitle, x: pages.equipment.processing, I: IconFactory}].map((group) => <div key={group.t} className="border border-white/15 bg-white/45 p-6 backdrop-blur-sm"><div className="flex items-center gap-4"><group.I className="h-8 w-8 shrink-0 text-biomass" aria-hidden /><h3 className="text-[12px] font-bold uppercase leading-tight tracking-[0.12em] text-biomass">{group.t}</h3></div><ul className="mt-5 flex flex-col gap-2.5">{group.x.map((x) => <li key={x} className="text-[13px] leading-snug text-stone-200">{x}</li>)}</ul></div>)}</div></SceneSection>
    <SceneSection num="05" eyebrow={pages.carbon.title} title={locale === "uk" ? "Вуглецеве партнерство" : "Carbon partnership"} lead={pages.carbon.lead} image="/images/regional-landscape.png" imagePosition="70% center" cta={dict.forms.configs.carbon.submit} href={p("/carbon")}><TickList items={pages.carbon.stack} /><p className="mt-6 text-[12px] leading-relaxed text-stone-300"><span className="mr-2 font-medium uppercase tracking-[0.15em] text-biomass">{pages.carbon.audienceTitle}</span>{pages.carbon.audience}</p><div className="mt-9 flex items-center gap-10"><div aria-hidden className="relative flex h-36 w-36 shrink-0 items-center justify-center rounded-full border border-biomass/50 bg-white/40 backdrop-blur-[2px]"><div className="absolute inset-3 rounded-full border border-biomass/20" /><div className="text-center"><p className="font-sans text-2xl font-light text-bone">CO₂</p><p className="mt-1 text-[9px] uppercase tracking-[0.3em] text-biomass">Removal</p></div></div><ul className="flex flex-col gap-2.5">{pages.carbon.chain.slice(1).map((w) => <li key={w} className="flex items-center gap-3 text-[12px] font-semibold uppercase tracking-[0.15em] text-stone-200"><span aria-hidden className="h-1 w-1 rounded-full bg-biomass" />{w}</li>)}</ul></div></SceneSection>
    <SceneSection num="06" eyebrow={pages.esg.title} title={pages.esg.subtitle} lead={pages.esg.lead} image="/images/esg-tablet-v2.png" imagePosition="70% center" cta={dict.forms.configs.esg.submit} href={p("/esg")}><TickList items={pages.esg.stack} /></SceneSection>
    <SceneSection num="07" eyebrow={pages.regionalPilots.title} title={pages.regionalPilots.subtitle} lead={pages.regionalPilots.lead} image="/images/regional-landscape.png" imagePosition="center" cta={dict.forms.configs.regionalPilot.submit} href={p("/regional-pilots")}><div className="flex flex-wrap items-start gap-x-1 gap-y-6">{pages.regionalPilots.model.map((step, i) => { const ChainIcons = [IconEarth, IconSoil, IconWater, IconGrass, IconSheaf, IconGear, IconCarbonLeaf, IconCoins]; const I = ChainIcons[i % ChainIcons.length]; return <span key={step} className="contents">{i > 0 && <span aria-hidden className="mb-8 hidden h-px w-7 border-t border-dashed border-biomass/40 sm:block" />}<span className="flex flex-col items-center gap-3"><I className="h-6 w-6 text-[#315b48]" aria-hidden /><span className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#294b3b]">{step}</span></span></span>; })}</div></SceneSection>
    <SceneSection num="08" eyebrow={pages.sciencePartners.title} title={pages.sciencePartners.subtitle} lead={pages.sciencePartners.lead} image="/images/science-lab.png" imagePosition="72% center" cta={dict.forms.configs.grantConsortium.submit} href={p("/science-partners")}><TickList items={pages.sciencePartners.directions} /><ol className="mt-8 flex flex-col">{pages.sciencePartners.model.map((step, i) => <li key={step} className="flex flex-col"><span className="flex items-center gap-4 py-2.5"><span className="w-7 text-right text-[11px] font-semibold tracking-[0.18em] text-biomass tabular-nums">{String(i + 1).padStart(2, "0")}</span><span aria-hidden className="h-px w-6 bg-biomass/40" /><span className="text-[13px] font-semibold uppercase tracking-[0.1em] text-stone-100">{step}</span></span>{i < pages.sciencePartners.model.length - 1 && <span aria-hidden className="ml-[34px] h-4 w-px bg-gradient-to-b from-biomass/55 to-transparent" />}</li>)}</ol></SceneSection>

    <section className="relative overflow-hidden bg-[#f8f7f2] px-6 py-24 text-[#15241d] sm:px-10 lg:px-14"><div aria-hidden className="absolute inset-0 bg-cover bg-center opacity-[.07]" style={{ backgroundImage: "url(/images/router-field.png)" }} /><div className="relative mx-auto max-w-[1440px]"><Reveal><p className="text-center text-[11px] font-semibold uppercase tracking-[.32em] text-[#315b48]">{h.path.kicker}</p><h2 className="mx-auto mt-4 max-w-4xl text-center font-serif text-[clamp(2.2rem,4vw,4rem)] uppercase leading-[1.02] tracking-[-0.01em]">{h.path.label}</h2><p className="mx-auto mt-5 max-w-2xl text-center text-[11px] font-medium uppercase leading-6 tracking-[.18em] text-[#526158]">{h.path.sublead}</p></Reveal><Reveal delay={0.12} className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{h.path.options.map((opt, i) => <Link key={opt.id} href={p(opt.href)} className="group flex min-h-[150px] flex-col items-center justify-center rounded-lg border border-[#173c2c]/15 bg-white/45 p-5 text-center transition-all duration-300 hover:-translate-y-1 hover:border-[#173c2c]/35 hover:bg-white/80"><span className="text-[#315b48]"><PathIcon index={i} className="h-7 w-7" /></span><h3 className="mt-4 text-[13px] font-semibold leading-snug">{opt.title}</h3><p className="mt-1 text-[10px] leading-4 text-[#637067]">{opt.desc}</p></Link>)}</Reveal></div></section>
    <section className="relative flex min-h-[720px] items-center justify-center overflow-hidden bg-[#f8f7f2] text-center text-[#15241d]"><div aria-hidden className="absolute inset-0 bg-cover bg-center brightness-[1.12] saturate-[.75]" style={{ backgroundImage: "url(/images/regional-landscape.png)" }} /><div aria-hidden className="absolute inset-0 bg-[linear-gradient(180deg,rgba(248,247,242,.86),rgba(248,247,242,.38)_52%,rgba(248,247,242,.82))]" /><Reveal className="relative max-w-5xl px-6"><p className="text-xs uppercase tracking-[.3em] text-[#315b48]">Vital Energy Miscanthus</p><h2 className="mt-7 font-serif text-[clamp(3rem,7vw,6.5rem)] font-normal uppercase leading-[0.98] tracking-[-0.02em]">{h.final.big[0]}<br />{h.final.big[1]}</h2><p className="mx-auto mt-7 max-w-2xl text-xs uppercase tracking-[.15em] text-[#42554b]">Regenerative bioeconomy · Circular economy · Low-carbon industry</p><div className="mx-auto mt-12 grid max-w-3xl grid-cols-2 gap-8 sm:grid-cols-4">{h.final.values.map((v, i) => { const VI = [IconPlanet, IconCommunity, IconCycle, IconFuture][i % 4]; return <div key={v} className="flex flex-col items-center gap-3"><VI className="h-7 w-7 text-[#234b38]" aria-hidden /><span className="text-[11px] font-medium uppercase tracking-[0.12em] text-[#34463d]">{v}</span></div>; })}</div><div className="mt-10"><CtaLink href={`${p("/contact")}?form=partnership`}>{dict.forms.configs.strategic.submit}<span>→</span></CtaLink></div></Reveal></section>
    <SiteFooter dict={dict} locale={locale} />
  </main>;
}
